### ISSUE TITLE
Skekdog's Sheepy Text

### ISSUE THREAD

**Issue by Skekdog** [RealBamboolord/Sheep-Meta#3]
An unfinished list of city names, all with some sort of tragic sheep pun

- Baamingham
- Mossheep
- Baarcelona
- Washearton
- Warwickshear
- Colorasheep
- Ramburgh

An unfinished list of quotes:

Attacked:
- What's that? Wolves dare come near me? How baamusing.

Defeated:
- Baah, you baarely did anything... shear luck must have been on your side..

Declaring War: 
- Baask (or however it is spelt but with baa) in my glory - for it is one you will have to get used to.

**Comment by RealBamboolord** [comment]
Alright

**Comment by RealBamboolord** [comment]
I added em in. I will leave this issue open for future names

**Comment by RealBamboolord** [comment]
Added secons push

**Comment by RealBamboolord** [comment]
took only a year to close ;)
